name: Build and Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
      - feature/github-actions

env:
  AZURE_CONTAINER_REGISTRY: acr4453beren.azurecr.io
  IMAGE_NAME: springboot-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: ./mvnw clean package

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME .
    
    - name: Push image to ACR
      run: |
        docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME
